### ISSUE TITLE
寻求training code

### ISSUE THREAD

**Issue by ZNHzlq** [RockWenJJ/SyreaNet#1]
尊敬的作者：
你好！
请问可以分享一下train.py吗？

**Comment by RockWenJJ** [comment]
> 尊敬的作者： 你好！ 请问可以分享一下train.py吗？

你好，我们仍然在整理训练代码。但由于目前我们仍然在优化目前的框架，所以训练代码的释放可能需要再等一等。我们会在不久的将来公开我们的训练代码。
We are sorting out the training code. But as we are currently still improving the existing framework,  you may need to wait some time for the release of the training code. We will make our training code public in the near future.

**Comment by ZNHzlq** [comment]
感谢你的答复，期待优秀作品的公布！！！

**Comment by ZNHzlq** [comment]
> > 尊敬的作者： 你好！ 请问可以分享一下train.py吗？
> 
> 你好，我们仍然在整理训练代码。但由于目前我们仍然在优化目前的框架，所以训练代码的释放可能需要再等一等。我们会在不久的将来公开我们的训练代码。 We are sorting out the training code. But as we are currently still improving the existing framework, you may need to wait some time for the release of the training code. We will make our training code public in the near future.

感谢你的答复，期待优秀作品的公布！！！

**Comment by Daa98** [comment]
期待更新!
